name: Feature Request
title: "[FEAT] ..."
description: Suggest an idea for this project.
labels: ["enhancement", "suggestion"]
body:
- type: markdown
  attributes:
    value: "## Thanks for filling this out!"

- type: textarea
  id: describe
  attributes:
    label: Related to a problem
    description: "Is your feature request related to a problem? Please describe."
  validations:
    required: false

- type: textarea
  id: solution
  attributes:
    label: Your Solution
    description: "A clear and concise description of what you want to happen."
  validations:
    required: true

- type: textarea
  id: alternatives
  attributes:
    label: Alternatives
    description: "Describe alternatives you've considered."
  validations:
    required: false

- type: textarea
  id: additional
  attributes:
    label: Additional Context
    description: "Add any other context or screenshots about the feature request here."
  validations:
    required: false
